ua-books/ua-books

app/views/layouts/application.slim

a side question:
- does the cloud66 deserve the button ? 
if they are free for the volunteering project, then "yes", otherwise...
another side question:
- you are writing labels' text right in the templates / code. 
Wouldn't it be better to keep them in the DB ?
It would allow future admins / moderators to fix / change them w/o your involvement.
Though, I think, you are doing it this way, b/c it is simpler at this stage.
Probably I'm just over-engineering it.
---
The side questions should be removed from the commit itself via "squashing"
It wasn't my intention.
Usually I'm not doing the PRs via github's "Edit" button, so I just didn't know
that it goes to the commit. Sorry.

Update the copyright's year

---

app/controllers/admin/books_controller.rb
app/controllers/admin/works_controller.rb
app/views/admin/books/_form.slim
app/views/admin/works/_index_header.slim
config/locales/admin.yml
spec/features/admin/books_spec.rb
spec/features/admin/works_spec.rb

The following steps are expected:
1) create book draft,
2) redirected to book's works page,
3) add new work,
4) back to step 2), repeat.
Testing index pages were extracted to a separate spec
to make them less brittle.

Adjust "book create" workflow.

---

Gemfile.lock

https://nvd.nist.gov/vuln/detail/CVE-2017-18258

Bump nokogiri (security update).

---

app/policies/admin/application_policy.rb
app/views/admin/application/index.slim
spec/policies/admin/book_policy_spec.rb
spec/policies/admin/person_policy_spec.rb
spec/policies/admin/publisher_policy_spec.rb
spec/policies/admin/work_policy_spec.rb
spec/policies/admin/work_type_policy_spec.rb

The scope follows the same rules as `index?` permission.

Use policy scope in /admin

---

app/policies/admin/person_policy.rb
spec/policies/admin/person_policy_spec.rb

Once new person is created it can be edited only by an admin. This is to prevent accidental editing of data that is shared between several publishers.

Allow a publisher to create people

---

app/assets/stylesheets/admin/form.scss
app/controllers/admin/books_controller.rb
app/inputs/uploadcare_input.rb
app/models/book.rb
app/models/uploadcare.rb
app/views/admin/books/_form.slim
config/locales/forms.yml
config/uploadcare.yml
db/migrate/20190303154345_add_cover_url_to_books.rb
db/structure.sql
spec/factories/book.rb
spec/features/admin/books_spec.rb
spec/models/uploadcare_spec.rb

This is part 1 of the migration.
In this one admin form is switched to Uploadcare widget.
When all images will be re-uploaded, we can remove dragonfly remains.

Switch image uploading to https://uploadcare.com

---

db/migrate/20190526161252_remove_books_cover_uid.rb
db/seeds.rb
db/structure.sql

This is final part of [the migration](https://github.com/ua-books/ua-books/issues/33).
Also the system/dragonfly directory was removed manually from the production server.

Remove Dragonfly's Book#cover_uid column

---

Gemfile
Gemfile.lock
config/application.rb

It was only used for caching assets generated on the fly
by dragonfly.
This reverts commit 02d3c6653c12ba774cab08bd5f8e3f88dbcbac68.
This is a cleanup after [the migration](https://github.com/ua-books/ua-books/issues/33).

rack-cache is no longer needed.

---

app/assets/stylesheets/application/footer_container.scss
app/views/layouts/application.slim

This reverts commit bca27b1c7cfe35c593bdebcb08fbdd92906272aa.
Cloud66 [no longer provides a free plan](https://www.cloud66.com/rails/pricing/). ua-books had to switch to a paid plan, so we don't have to show their banner.

Revert "Apply for free service from cloud66.com."

---

Gemfile.lock

https://github.com/ua-books/ua-books/pull/49 prevented cookies to be set (see [notes](https://github.com/puma/puma/blob/master/History.md#433-and-3124--2020-02-28))

Bump puma (bugfix after a security fix).

---

config/initializers/dragonfly.rb

This is part 2 for [the migration](https://github.com/ua-books/ua-books/issues/45).
It allows a developer to upload her/his own covers to s3. This way we don't have to have a special image processing proxy in development and can benefit from the same production proxy (currently imagekit.io).
IAM user is specified as write-only *and* is scoped to /dev folder, so that an attacker can't use them to overwrite/delete production images:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "VisualEditor0",
"Effect": "Allow",
"Action": [
"s3:PutObject",
"s3:DeleteObject",
"s3:GetBucketLocation"
],
"Resource": [
"arn:aws:s3:::ua-books",
"arn:aws:s3:::ua-books/dev/*"
]
}
]
}
```
See markevans/dragonfly-s3_data_store#30 (comment) on why s3:GetBucketLocation is needed.

Allow to upload images in development

---

app/controllers/admin/books_controller.rb
app/helpers/imagekit_helper.rb
app/views/books/show.slim
app/views/sitemap/show.xml.slim
spec/requests/sitemap_spec.rb

This is part 3 for [the migration](https://github.com/ua-books/ua-books/issues/45).
It uses https://imagekit.io/ as an image processing proxy.
AWS S3 bucket is specified as a [source](https://docs.imagekit.io/integration/configure-origin/amazon-s3-bucket-origin). IAM policy is read-only:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "VisualEditor0",
"Effect": "Allow",
"Action": "s3:GetObject",
"Resource": "arn:aws:s3:::ua-books/*"
}
]
}
```
Notice, this allows imagekit service to read both production (root) and dev/ files. That means a production dump would be still useful on a local machine.

Switch image processing to imagekit.io

---

app/models/work_type.rb

While manually adding new types via admin UI I managed to create duplicates even though the list was quite small. In the future this list will only grow, so does the probability of duplicates.
For now it's enough to have only AR-backed validation (no unique index in DB has been added).

Ensure work types have unique names

---

app/controllers/admin/authors_controller.rb
app/controllers/admin/works_controller.rb
app/controllers/home_controller.rb
app/controllers/publishers_controller.rb
app/helpers/application_helper.rb
app/models/author.rb
app/models/author_alias.rb
app/models/work.rb
app/views/admin/works/_form.slim
app/views/books/show.slim
app/views/sitemap/show.xml.slim
config/locales/forms.yml
db/migrate/20210110154703_rename_person_aliases_to_author_aliases.rb
db/seeds.rb
db/structure.sql
spec/features/admin/works_spec.rb
spec/features/books_spec.rb
spec/features/home_spec.rb
spec/features/publishers_spec.rb
spec/helpers/application_helper_spec.rb
spec/policies/admin/work_policy_spec.rb
spec/requests/sitemap_spec.rb

This is part 2 of the https://github.com/ua-books/ua-books/issues/63.
Renaming a table in place would lead to runtime exceptions in between the rename and code reload, but we do not care, since current traffic is zero (except for crawlers).

Rename "person_aliases" to "author_aliases"

---

app/models/author.rb
app/models/author_alias.rb
db/migrate/20210110161606_rename_person_id_to_author_id.rb
db/structure.sql

This is part 3 of the https://github.com/ua-books/ua-books/issues/63.
Renaming a column in place would lead to runtime exceptions in between the rename and code reload, but we do not care, since current traffic is zero (except for crawlers).

Rename AuthorAlias#person_id to #author_id

---

app/controllers/admin/works_controller.rb
app/helpers/application_helper.rb
app/models/work.rb
db/migrate/20210110163351_rename_person_alias_id_to_author_alias_id.rb
db/structure.sql

This is part 4 of the https://github.com/ua-books/ua-books/issues/63.
Renaming a column in place would lead to runtime exceptions in between the rename and code reload, but we do not care, since current traffic is zero (except for crawlers).

Rename Work#person_alias_id to #author_alias_id

---

config/routes.rb
spec/features/admin/authors_spec.rb
spec/features/admin/books_spec.rb
spec/features/admin/publishers_spec.rb
spec/features/admin/work_types_spec.rb
spec/features/admin/works_spec.rb
spec/features/authors_spec.rb
spec/features/books_spec.rb
spec/features/home_spec.rb
spec/features/publishers_spec.rb
spec/features/static_spec.rb
spec/requests/sitemap_spec.rb
spec/support/sign_in_as.rb

Benefits:
- allows to avoid string interpolation and URI escaping,
- more resilient to future changes to routes.

Use route helpers in specs

---

app/views/admin/application/index.slim
spec/features/admin/authors_spec.rb
spec/features/admin/work_types_spec.rb
spec/features/admin/works_spec.rb

By default slim does not add whitespaces between HTML tags.
That makes asserting text quite awkward:
```html
<td>First</td>
<td>Name</td>
```
```ruby
expect(page).to have_content "FirstName"
```
By manually [adding the whitespace](https://github.com/slim-template/slim#trailing-and-leading-whitespace--) to the markup we can write 
```ruby
expect(page).to have_content "First Name"
```

Have whitespace between columns in /admin

---

app/models/author_alias.rb
app/views/admin/works/_form.slim
spec/policies/admin/author_alias_policy_spec.rb

- sort aliases by last name first, then by first name on a "Create
work" screen,
- ensure uniqueness within the same author.

Admin improvements related to author aliases.

---

spec/factories/author_alias.rb
spec/policies/admin/author_alias_policy_spec.rb

This is a follow-up to https://github.com/ua-books/ua-books/pull/79.
Once we introduced unique validation for `AuthorAlias`, it became tedious to provide unique names for each alias in case many of them are created during a single spec. The whole purpose of factories is to omit those fields that we are not interested in right now, so let the factory be valid by default by ensuring the `first_name` field is unique ("Оксана (1)", "Оксана (2) etc).

Let AuthorAlias factory be valid by default

---

app/assets/stylesheets/admin.scss
app/controllers/admin/author_aliases_controller.rb
app/models/author.rb
app/models/author_alias.rb
app/policies/admin/author_alias_policy.rb
config/routes.rb
db/migrate/20210221153907_add_main_to_author_aliases.rb
db/structure.sql
spec/features/admin/author_aliases_spec.rb
spec/models/author_alias_spec.rb
spec/policies/admin/author_alias_policy_spec.rb

Previous approach was to treat an earliest author alias as main.
That does not allow to define an alias that has been added as an author's second/third one as main.
The new approach is to have an explicit `main` boolean flag set for only one of the author's aliases.

Explicitly define main AuthorAlias

---

spec/policies/admin/author_alias_policy_spec.rb
spec/policies/admin/author_policy_spec.rb
spec/policies/admin/book_policy_spec.rb
spec/policies/admin/publisher_policy_spec.rb
spec/policies/admin/work_policy_spec.rb
spec/policies/admin/work_type_policy_spec.rb

RSpec's `match` is strict with ordering of arrays. Usually Postgres returns
records in the order of records insertion, but this is not guaranteed, and from
time to time specs fail.
One solution is to ensure the order in tests/model before checking for results.
However, for policies spec we are not interested in the order of records
returned from DB, therefore let's use `match_array` which is order independent.

Use less strict `match_array`

---

app/models/work.rb
app/views/authors/show.slim
app/views/books/show.slim

`Author` model responds to `#first_name` and `#last_name`, and they are cached as per https://github.com/ua-books/ua-books/pull/81/files#diff-548e910ad2323ef8e4ceaaf47580763bd9be7ba609eacab124d48cdc56833fe9R21

No need to use Author#main_alias in views

---

app/controllers/authors_controller.rb
app/controllers/home_controller.rb
app/controllers/publishers_controller.rb
app/models/book.rb
app/models/work.rb
app/views/books/show.slim
app/views/sitemap/show.xml.slim

Previous approach was to extract the whole `.preload(:arg1, :arg2)` part in a `.for_list` class method.
This works great for an immediate association like `publisher.books.for_list`, but it can't be reused for nested preloads like `author.publisher.preload(books: cant_use_Book_for_list_here)`.
The new approach is to have a class method `.associations_to_preload` which holds only arguments for `.preload` in a form of array/hash. That makes `.preload` more explicit and can be used for nested preloads – `author.publisher.preload(books: Book.associations_to_preload)`.

Share common `preload` arguments as scope methods

---

app/helpers/json_ld_helper.rb
app/models/work.rb
app/models/work_type.rb
app/views/admin/work_types/_form.slim
app/views/books/show.slim
config/locales/forms.yml
db/migrate/20210411153603_add_schema_org_role_to_work_types.rb
db/structure.sql
spec/factories/work_type.rb
spec/features/admin/work_types_spec.rb
spec/helpers/json_ld_helper_spec.rb

It is unclear, does Google prefer pages with schema.org markup or not, especially when it comes to [Book format](https://schema.org/Book). Actually, it is even not clear, do they support it at all, because [this page](https://developers.google.com/search/docs/data-types/book) is only about feeds (enabled for large book providers only) and [test rich results](https://search.google.com/test/rich-results) shows no rich preview is supported for the page. Also Book format is not listed [here](https://support.google.com/webmasters/answer/7445569#zippy=,supported-types).
Still, it is possible that Google may rank such pages higher and does not advertise this.
[Review snippets](https://developers.google.com/search/docs/data-types/review-snippet) are definitely supported (to be implemented in the …

JSON-LD book schema

---

.circleci/config.yml

Related - https://github.com/ua-books/ua-books/pull/73
See the [request to include `psql` by default](https://github.com/CircleCI-Public/cimg-base/issues/91) in the Docker image.

Pre-installing `psql` is no longer needed on CircleCI

---

.circleci/config.yml

When a single gem version is changed in Gemfile.lock we completely discard previous gems cache on Circle CI and install everything from scratch.
Use master's cache, unpack it, then install over it, which will fetch only updated and/or new gems.
This was handled in https://github.com/CircleCI-Public/ruby-orb/pull/65

Use latest circleci/ruby orb
